# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Parth Mahajan

"""Retrieval-augmented answers over past sessions.

Retrieval and embeddings are fully local. The answer itself is generated by a
local CLI the user already has signed in (`claude` or `codex`), or by Ollama if
it is running. Both CLIs are invoked in non-persisting mode so asking a
question never creates a new transcript that would then get indexed.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import urllib.request
from collections.abc import Iterator

from . import store
from .search import Filters, hybrid_search, neighbors

SYSTEM = (
    "You answer questions about the user's own past coding-agent sessions "
    "(Claude Code and Codex transcripts). Use ONLY the numbered excerpts provided. "
    "Cite excerpts inline like [1] or [2][5]. If the excerpts don't contain the answer, "
    "say so plainly and mention what related material was found. Be concise and concrete: "
    "include commands, file paths, IDs and decisions verbatim when they matter."
)

PATH_EXTRA = ["/opt/homebrew/bin", "/usr/local/bin", os.path.expanduser("~/.local/bin")]
WORKDIR = store.DATA_DIR / "rag-workdir"


def _env() -> dict:
    env = dict(os.environ)
    env["PATH"] = ":".join(PATH_EXTRA + [env.get("PATH", "/usr/bin:/bin")])
    return env


def _which(cmd: str) -> str | None:
    return shutil.which(cmd, path=_env()["PATH"])


def _ollama_models() -> list[str]:
    try:
        with urllib.request.urlopen("http://127.0.0.1:11434/api/tags", timeout=0.5) as r:
            return [m["name"] for m in json.load(r).get("models", [])]
    except Exception:
        return []


def providers() -> list[dict]:
    out = []
    if _which("claude"):
        out.append({"id": "claude", "label": "Claude Code CLI", "models": ["haiku", "sonnet", "opus"]})
    if _which("codex"):
        out.append({"id": "codex", "label": "Codex CLI", "models": ["default"]})
    models = _ollama_models()
    if models:
        out.append({"id": "ollama", "label": "Ollama (fully local)", "models": models})
    return out


def build_context(question: str, f: Filters, k: int = 10) -> tuple[list[dict], str]:
    hits = hybrid_search(question, f, limit=k, per_session=2)
    conn = store.connect()
    try:
        blocks = []
        for i, h in enumerate(hits, 1):
            ctx = neighbors(conn, h["session_key"], h["seq"], radius=1)
            body = "\n".join(f"{c['role'].upper()}: {c['text']}" for c in ctx)[:3500]
            h["n"] = i
            blocks.append(
                f"[{i}] {h['source']} session \"{h['title']}\" | project {h['cwd']} | {h['updated_at'] or ''}\n{body}"
            )
    finally:
        conn.close()
    prompt = (
        f"{SYSTEM}\n\n=== EXCERPTS ===\n\n" + "\n\n---\n\n".join(blocks)
        + f"\n\n=== QUESTION ===\n{question}\n"
    )
    return hits, prompt


def _stream_claude(prompt: str, model: str) -> Iterator[str]:
    WORKDIR.mkdir(parents=True, exist_ok=True)
    cmd = [
        _which("claude") or "claude", "-p", "--no-session-persistence", "--tools", "",
        "--model", model or "haiku", "--output-format", "stream-json", "--verbose",
        "--include-partial-messages",
        # Skip MCP servers, hooks, plugins and skills: cuts CLI startup from ~8s to ~3s.
        "--strict-mcp-config", "--setting-sources", "", "--disable-slash-commands",
    ]
    proc = subprocess.Popen(
        cmd, cwd=WORKDIR, env=_env(), stdin=subprocess.PIPE, stdout=subprocess.PIPE,
        stderr=subprocess.PIPE, text=True,
    )
    proc.stdin.write(prompt)
    proc.stdin.close()
    got_delta = False
    for line in proc.stdout:
        try:
            ev = json.loads(line)
        except ValueError:
            continue
        if ev.get("type") == "stream_event":
            d = ev.get("event", {}).get("delta", {})
            if d.get("type") == "text_delta":
                got_delta = True
                yield d["text"]
        elif ev.get("type") == "result":
            if ev.get("is_error"):
                yield f"\n\n**Error from claude:** {ev.get('result')}"
            elif not got_delta and ev.get("result"):
                yield ev["result"]
    proc.wait()
    if proc.returncode and not got_delta:
        yield f"\n\n**claude exited {proc.returncode}:** {proc.stderr.read()[-800:]}"


def _stream_codex(prompt: str, model: str) -> Iterator[str]:
    WORKDIR.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("r", suffix=".txt", delete=False) as out:
        out_path = out.name
    cmd = [
        _which("codex") or "codex", "exec", "--ephemeral", "--skip-git-repo-check",
        "-s", "read-only", "-o", out_path,
    ]
    if model and model != "default":
        cmd += ["-m", model]
    cmd.append("-")
    proc = subprocess.run(
        cmd, cwd=WORKDIR, env=_env(), input=prompt, capture_output=True, text=True, timeout=600
    )
    try:
        text = open(out_path).read().strip()
    finally:
        os.unlink(out_path)
    yield text or f"**codex exited {proc.returncode}:** {proc.stderr[-800:]}"


def _stream_ollama(prompt: str, model: str) -> Iterator[str]:
    body = json.dumps({"model": model, "prompt": prompt, "stream": True}).encode()
    req = urllib.request.Request(
        "http://127.0.0.1:11434/api/generate", data=body, headers={"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=600) as r:
        for line in r:
            ev = json.loads(line)
            if ev.get("response"):
                yield ev["response"]


def answer(prompt: str, provider: str, model: str) -> Iterator[str]:
    if provider == "codex":
        return _stream_codex(prompt, model)
    if provider == "ollama":
        return _stream_ollama(prompt, model)
    return _stream_claude(prompt, model)
